### ISSUE TITLE
The license of org.eclipse.jetty.toolchain:jetty-servlet-api is much more strict than comparable jars

### ISSUE THREAD

**Issue by amsmax** [eclipse/jetty.toolchain#143]
**Jetty version(s)**
not applicable

**Java version/vendor** `(use: java -version)`
not applicable

**OS type/version**
not applicable

**Description**
The following library causes a build breaker in Nexus IQ due to a license issue.
`<dependency>
    <groupId>org.eclipse.jetty.toolchain</groupId>
    <artifactId>jetty-servlet-api</artifactId>
    <version>4.0.6</version>
</dependency>`

The jar contains 3 licenses. The Eclipse license an Apache License and the GNU license. The GNU license causes the issue. Especially the part. '## CLASSPATH EXCEPTION' 

A comparable jar e.g. 
`<dependency>
    <groupId>org.apache.tomcat</groupId>
    <artifactId>tomcat-servlet-api</artifactId>
    <version>9.0.55</version>
</dependency>`

has only the Apache License. Is it possible to remove the GNU License?

**How to reproduce?**
not applicable

**Comment by joakime** [comment]
Moved this to the `jetty.toolchain` repository, where this artifact is housed.

**Comment by amsmax** [comment]
Note that jakarta.servlet:jakarta.servlet-api:4.0.4 doesn't have a license at all. At least I cannot find it in the jar.

https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/4.0.4/jakarta.servlet-api-4.0.4.jar

**Comment by joakime** [comment]
Looks like the bump to toolchain parent 1.7 fixed the missing META-INF/LICENSE.md

https://github.com/eclipse/jetty.toolchain/commit/221be58557348bc868068913b500f0c8cb1f3153#diff-a067503d2af24e2f8dad6a2a5e17a55ec84a72561c42475ac259f229eca2ea10R5

**Comment by joakime** [comment]
The SPDX identifier is still set properly in our 4.0.4 aggregate jar

```
[servlet-investigation]$ curl -O https://repo1.maven.org/maven2/org/eclipse/jetty/toolchain/jetty-servlet-api/4.0.4/jetty-servlet-api-4.0.4.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  590k  100  590k    0     0  2878k      0 --:--:-- --:--:-- --:--:-- 2892k
[servlet-investigation]$ jar -xvf jetty-servlet-api-4.0.4.jar META-INF/NOTICE.md
 inflated: META-INF/NOTICE.md
[servlet-investigation]$ grep SPDX META-INF/NOTICE.md 
SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
```

The official jakarta.servlet-api:4.0.4 has a license declared as well.

```
$ curl -O https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/4.0.4/jakarta.servlet-api-4.0.4.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 82973  100 82973    0     0   604k      0 --:--:-- --:--:-- --:--:--  604k
$ jar -xvf jakarta.servlet-api-4.0.4.jar META-INF/MANIFEST.MF
 inflated: META-INF/MANIFEST.MF
$ grep -A1 Bundle-License META-INF/MANIFEST.MF 
Bundle-License: http://www.eclipse.org/legal/epl-2.0, https://www.gnu.
 org/software/classpath/license.html
```

And the official jar also has it declared in the metadata.

```
$ curl -O https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/4.0.4/jakarta.servlet-api-4.0.4.pom
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17106  100 17106    0     0   153k      0 --:--:-- --:--:-- --:--:--  154k
$ grep -A2 -B2 "license>" jakarta.servlet-api-4.0.4.pom 

    <licenses>
        <license>
            <name>EPL 2.0</name>
            <url>http://www.eclipse.org/legal/epl-2.0</url>
            <distribution>repo</distribution>
        </license>
        <license>
            <name>GPL2 w/ CPE</name>
            <url>https://www.gnu.org/software/classpath/license.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

```

**Comment by joakime** [comment]
Ah, looks like this licensing here is even more complicated then it seems for the servlet-api (apparently due to the age of the servlet spec)

See https://github.com/eclipse-ee4j/servlet-api/issues/347

**Comment by joakime** [comment]
The official SPDX for license on the servlet spec is ...

```
SPDX-License-Identifier: (EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0) AND Apache-2.0
```

I'll make sure both the LICENSE.md and NOTICE.md here are updated to reflect that.

**Comment by joakime** [comment]
Opened PR #144 to fix `SPDX-License-Identifier` in use by this aggregate jar.
