### ISSUE TITLE
Migrate jetty-osgi-servlet-api artifact to jetty-servlet-api

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.toolchain#20]
Along with the required build fixes from #18, we should perform the necessary steps from eclipse/jetty.project#3120 to bring this artifact up to speed for JPMS as well.

Current tasks:

* Rename to `jetty-servlet-api`
* Implement build fixes from #18 
* Add JPMS `module-info.java` that depends on `jetty-schemas`

**Comment by sbordet** [comment]
@joakime while we're at it, we need to add `Automatic-Module-Name: jetty.servlet.api` to the manifest, so Jetty 10.0.x can properly reference it.

**Comment by joakime** [comment]
Example of new generated `META-INF/MANIFEST.MF`

```
Manifest-Version: 1.0
Automatic-Module-Name: jetty-servlet-api
Bnd-LastModified: 1543251475166
Build-Jdk: 9
Built-By: joakim
Bundle-Description: Combined servlet api and schemas for use in JPMS and
  OSGi environments
Bundle-DocURL: http://www.mortbay.com
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0, http://www.e
 clipse.org/org/documents/epl-v10.php
Bundle-ManifestVersion: 2
Bundle-Name: Jetty Servlet API and Schemas for JPMS and OSGi
Bundle-RequiredExecutionEnvironment: JavaSE-1.7
Bundle-SymbolicName: org.eclipse.jetty.osgi-servlet-api
Bundle-Vendor: Mort Bay Consulting
Bundle-Version: 4.0.0.SNAPSHOT
Created-By: Apache Maven Bundle Plugin
Implementation-Vendor: Eclipse.org - Jetty
Implementation-Version: 4.0-SNAPSHOT
Tool: Bnd-3.5.0.201709291849
url: http://www.eclipse.org/jetty
```

**Comment by sbordet** [comment]
Should not we require `JavaSE-1.8`?

**Comment by joakime** [comment]
the `JavaSE-1.7` update to the OSGi environment settings for Servlet API 4.0 was done by @janbartel in commit 46bd54b14430eda4f4c8e1a243644462e680352a
Didn't feel appropriate to adjust that.

**Comment by sbordet** [comment]
@joakime the `Automatic-Module-Name` is wrong, as module names cannot contain the `-` character.
Can you please use `jetty.servlet.api`?

**Comment by joakime** [comment]
This work has been completed
