### ISSUE TITLE
Please include license files

### ISSUE THREAD

**Issue by msimacek** [eclipse/jetty.toolchain#5]
Both ASL and EPL licenses require the full license texts to be distributed alongside the software. Please include them in the source repository.

**Comment by joakime** [comment]
This toolchain project is a collection of separate builds for mostly for internal artifacts that are not distributed (in the traditional sense).

Are there some specific artifacts that are missing these license files?  
If so, then we need to correct for that specific artifact.

**Comment by msimacek** [comment]
I maintain jetty package for Fedora and Fedora requires everything to be built from source, including build-only dependencies. So I have to redistribute those artifacts in order to be able to build jetty.

> Are there some specific artifacts that are missing these license files?
Well, all of them (except jetty-distribution-remote-resources). I'm currently interested in jetty-setuid and jetty-test-helper. I can submit a pull request if you want.

**Comment by aslaski** [comment]
Hi Simone!
Greetings from Atlassian

My project depends on apache-jsp, which depends on **jetty-schemas**. For legal reasons licenses for all our dependencies must be explicitly stated. Can you help with this?

Regards,
Adam

**Comment by joakime** [comment]
@aslaski we are preparing the 9.4.13 release, I'll make sure these 3 artifacts have the appropriate LICENSE and NOTICE files:

* jetty-schemas (see #15)
* jetty-setuid (see #16)
* jetty-test-helper (see #17)

**Comment by joakime** [comment]
@aslaski jetty-schemas 3.1.1 and 4.0.2 are now on maven central.

**Comment by joakime** [comment]
Also, @aslaski know that the licenses are declared in the pom, which is in the JAR already, and is a requirement to for any artifact (with source) to exist on maven central.

All other requests for LICENSE / NOTICE will be handled in other issues.

**Comment by aslaski** [comment]
Many thanks @joakime
