### ISSUE TITLE
Import jetty-admin code templates

### ISSUE THREAD

**Issue by gregw** [eclipse/jetty.toolchain#9]
The jetty admin repo has not been migrated to github.
It would be good to have the files:
 - `idea-jetty-codestyle-settings.jar`
 - `jetty-eclipse-codetemplates.xml`
 - `jetty-eclipse-java-format.xml`
 - `eclipse-jetty-templates.xml`

more accessible, so perhaps move them to jetty-toolchain

**Comment by janbartel** [comment]
I think this issue has been addressed by the inclusion of the checkstyle files, and eclipse and intellij  style files in the main jetty repo under build-resources/.
